const DEFAULT_TITLE = "Positron";
const DEFAULT_DESCRIPTION = "Reduce the amount of hate and misinformation";
const DEFAULT_BASE_URL = "https://positron.com/";

const CONSTANTS = {
  DEFAULT_TITLE: DEFAULT_TITLE,
  DEFAULT_AUTHOR: "HackED 2024",
  DEFAULT_DESCRIPTION: DEFAULT_DESCRIPTION,
  DEFAULT_KEYWORDS: ["Positron"],
  DEFAULT_SITE_NAME: "Positron",
  DEFAULT_BASE_URL: DEFAULT_BASE_URL,
  DEFAULT_PREVIEW_IMG: "https://positron.com/ogimage.png",
  DEFAULT_TWITTER_TITLE: DEFAULT_TITLE,
  DEFAULT_TWITTER_DESCRIPTION: DEFAULT_DESCRIPTION,
  DEFAULT_GOOGLE_ANALYTICS: "G-KLVV6HWCRZ",
};

export default CONSTANTS;
